### ISSUE TITLE
4.06/trunk support

### ISSUE THREAD

**Issue by hhugo** [let-def/migrate-parsetree#19] opened 2017-05-21 12:44 UTC

**Comment by let-def** [comment] 2017-05-31 09:42
I just pushed trunk support. Tell me if it works for you.

**Comment by aantron** [comment] 2017-07-22 14:59
I believe OMP was working on 4.06+trunk for a while. However, we now [get](https://travis-ci.org/ocsigen/lwt/jobs/256376561#L643):

```
File "src/ast_406.ml", line 556, characters 2-454:
Error: This variant or record definition does not match that of type
         Parsetree.class_type_desc
       The field Pcty_open is only present in the original definition.
```

Probably caused by https://github.com/ocaml/ocaml/pull/1249 being merged into `trunk`.

**Comment by let-def** [comment] 2017-07-24 14:49
Thanks, I just synchronized with trunk.

**Closed as completed by let-def** 2017-07-24 14:49 UTC
