### ISSUE TITLE
module open in patterns failing on ocaml 4.04

### ISSUE THREAD

**Issue by avsm** [let-def/migrate-parsetree#18] opened 2017-05-08 15:04 UTC
When using OCaml 4.04.0 with this line

```
    function
    | Opam_bulk_build_diff_key.(Remote {o;n;ocaml_version;distro}) ->
        Fmt.strf "Diffing %d -> %d packages (%s-%a)"
         (List.length o) (List.length n) distro OV.pp ocaml_version
```

I am getting a migrate-parsetree exception:

```
Fatal error: exception File "src/opam_bulk_build_diff.ml", line 41, characters 6-66: module open in patterns are not supported before OCaml 4.04
Raised at file "src/migrate_parsetree_404_403_migrate.ml", line 24, characters 2-49
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 260, characters 8-46
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 223, characters 8-29
Called from file "list.ml", line 59, characters 20-23
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 63, characters 8-31
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 37, characters 8-49
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 69, characters 10-30
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 37, characters 8-49
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 244, characters 8-34
Called from file "list.ml", line 59, characters 20-23
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 502, characters 10-42
Called from file "src/migrate_parsetree_404_403_migrate.ml", line 485, characters 8-44
```

However, I am in fact on OCaml 4.04.0, so presumably shouldn't be getting this failure?

**Comment by let-def** [comment] 2017-05-08 15:07
It's when migrating from 4.04 to 4.03, so one of the rewriter needs 4.03 syntax.
Right now it raises a failure, in the future this could be encoded using attributes.

**Comment by avsm** [comment] 2017-05-08 15:08
hm i was using ppx_sexp_conv -- i guess the released version needs 4.03

**Comment by antoine1fr** [comment] 2017-11-17 10:48
I think I've run into a similar problem using local exceptions. It happened once using ppx_deriving 4.2 and oasis, and a second time with ppx_sexp_conv v0.9.0 and jbuilder. Both ppx_deriving 4.2 and ppx_sexp_conv use ocaml-migrate-parsetree if I understand correctly.

Here is the link to the initial issue I created on ppx_sexp_conv's bug tracker: https://github.com/janestreet/ppx_sexp_conv/issues/17.

What is the status on this issue?

**Comment by XVilka** [comment] 2020-04-15 12:28
Should this one be closed as outdated now?

**Comment by aantron** [comment] 2020-04-15 12:36
Yes, thanks.

The issue is caused specifically by a PPX using a 4.03 or earlier AST during rewriting, even if the installed OCaml version is higher.

**Closed as completed by aantron** 2020-04-15 12:36 UTC
